[general]
current_preset = 2
path = "C:/Users/adablanc/Music/YT-DLP-GUI/Diversity"
# Argument global (ex: "--proxy 127.0.0.1")
global_args = ""
# Mise à jour automatique de yt-dlp au lancement
update_ytdlp = true

# --- PARAMÈTRES DE SÉCURITÉ ---
# Navigateurs supportés : "brave", "chrome", "chromium", "edge", "firefox", "opera", "safari", "vivaldi"
cookie_browser = ""
# Délai en secondes entre chaque vidéo pour éviter le bannissement IP
sleep_interval = 5

[presets]
best = "-f bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b"
mp4 = "-f bv*[vcodec^=avc]+ba[ext=m4a]/b"
# Preset MP3 avec pochette d'album et métadonnées incluses
mp3 = "--extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata --no-abort-on-error"
# wav = "--extract-audio --audio-format wav --audio-quality 0"